package com.obsidianscout.collab

import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put

/**
 * Operation engine for live config editing. The same rules are implemented in
 * static/js/services/config-collab.js and the app's lib/services/config_collab/config_sync_engine.dart;
 * all three must stay in step (src/test/resources/config-collab-vectors.json checks them).
 *
 * A document is a config JSON object. Its `fields` array is addressed by per-field keys that are stable
 * for one room epoch (they are not stored in the config), so concurrent edits to different fields, or
 * different properties of the same field, merge instead of overwriting each other.
 *
 * Ops:
 *  {"op":"set","path":[...],"value":V}      top-level path, or ["fields", key, ...props]
 *  {"op":"unset","path":[...]}
 *  {"op":"insert","key":K,"after":K|null,"value":V}
 *  {"op":"delete","key":K}
 *  {"op":"move","key":K,"after":K|null}
 * Ops that reference a key that no longer exists are no-ops; `after` pointing at a missing key means "at the end".
 */
data class KeyedDoc(val doc: JsonObject, val keys: List<String>) {
    val fields: List<JsonElement> get() = ConfigSyncEngine.fieldsOf(doc)
}

data class DiffResult(val ops: List<JsonObject>, val keys: List<String>)

class InvalidOpException(message: String) : IllegalArgumentException(message)

object ConfigSyncEngine {
    const val FIELDS = "fields"
    private const val MAX_PATH_DEPTH = 8
    private const val MAX_SEGMENT_LENGTH = 128
    private const val MAX_KEY_LENGTH = 64

    fun fieldsOf(doc: JsonObject): List<JsonElement> = (doc[FIELDS] as? JsonArray) ?: emptyList()

    /** Wraps a plain config with keys generated by [newKey]. */
    fun keyed(doc: JsonObject, newKey: () -> String): KeyedDoc {
        val normalized = ensureFields(doc)
        return KeyedDoc(normalized, fieldsOf(normalized).map { newKey() })
    }

    // ── Validation ─────────────────────────────────────────────────────────────

    /** Throws [InvalidOpException] if [op] is not a well-formed operation. */
    fun validate(op: JsonElement) {
        val obj = op as? JsonObject ?: throw InvalidOpException("op must be an object")
        when (stringOrNull(obj["op"])) {
            "set" -> {
                validatePath(obj["path"])
                if (!obj.containsKey("value")) throw InvalidOpException("set requires value")
            }
            "unset" -> validatePath(obj["path"])
            "insert" -> {
                validateKey(obj["key"])
                validateAfter(obj["after"])
                if (!obj.containsKey("value")) throw InvalidOpException("insert requires value")
            }
            "delete" -> validateKey(obj["key"])
            "move" -> {
                validateKey(obj["key"])
                validateAfter(obj["after"])
            }
            else -> throw InvalidOpException("unknown op")
        }
    }

    private fun validatePath(path: JsonElement?) {
        val arr = path as? JsonArray ?: throw InvalidOpException("path must be an array")
        if (arr.isEmpty() || arr.size > MAX_PATH_DEPTH) throw InvalidOpException("bad path length")
        arr.forEach {
            val s = stringOrNull(it) ?: throw InvalidOpException("path segments must be strings")
            if (s.length > MAX_SEGMENT_LENGTH) throw InvalidOpException("path segment too long")
        }
    }

    private fun validateKey(key: JsonElement?) {
        val s = stringOrNull(key) ?: throw InvalidOpException("key must be a string")
        if (s.isEmpty() || s.length > MAX_KEY_LENGTH) throw InvalidOpException("bad key")
    }

    private fun validateAfter(after: JsonElement?) {
        if (after == null || after is JsonNull) return
        validateKey(after)
    }

    // ── Applying ───────────────────────────────────────────────────────────────

    fun applyOps(state: KeyedDoc, ops: List<JsonElement>): KeyedDoc = ops.fold(state) { acc, op -> applyOp(acc, op) }

    fun applyOp(state: KeyedDoc, op: JsonElement): KeyedDoc {
        val o = op as? JsonObject ?: return state
        return when (stringOrNull(o["op"])) {
            "set" -> setOrUnset(state, pathOf(o), o["value"] ?: JsonNull, unset = false)
            "unset" -> setOrUnset(state, pathOf(o), null, unset = true)
            "insert" -> insert(state, stringOrNull(o["key"]) ?: return state, afterOf(o), o["value"] ?: JsonNull)
            "delete" -> delete(state, stringOrNull(o["key"]) ?: return state)
            "move" -> move(state, stringOrNull(o["key"]) ?: return state, afterOf(o))
            else -> state
        }
    }

    private fun pathOf(o: JsonObject): List<String> =
        (o["path"] as? JsonArray)?.mapNotNull { stringOrNull(it) } ?: emptyList()

    private fun afterOf(o: JsonObject): String? = stringOrNull(o["after"])

    private fun setOrUnset(state: KeyedDoc, path: List<String>, value: JsonElement?, unset: Boolean): KeyedDoc {
        if (path.isEmpty()) return state
        if (path[0] != FIELDS) {
            val doc = if (unset) unsetIn(state.doc, path) else setIn(state.doc, path, value!!)
            return state.copy(doc = doc)
        }
        if (path.size < 2) return state
        val idx = state.keys.indexOf(path[1])
        if (idx < 0) return state
        val fields = state.fields.toMutableList()
        if (path.size == 2) {
            if (unset) return state
            fields[idx] = value!!
        } else {
            val field = fields[idx] as? JsonObject ?: return state
            val rest = path.subList(2, path.size)
            fields[idx] = if (unset) unsetIn(field, rest) else setIn(field, rest, value!!)
        }
        return state.copy(doc = withFields(state.doc, fields))
    }

    private fun setIn(obj: JsonObject, path: List<String>, value: JsonElement): JsonObject {
        val head = path[0]
        if (path.size == 1) return JsonObject(obj + (head to value))
        val child = obj[head] as? JsonObject ?: JsonObject(emptyMap())
        return JsonObject(obj + (head to setIn(child, path.subList(1, path.size), value)))
    }

    private fun unsetIn(obj: JsonObject, path: List<String>): JsonObject {
        val head = path[0]
        if (path.size == 1) return if (obj.containsKey(head)) JsonObject(obj - head) else obj
        val child = obj[head] as? JsonObject ?: return obj
        return JsonObject(obj + (head to unsetIn(child, path.subList(1, path.size))))
    }

    private fun insert(state: KeyedDoc, key: String, after: String?, value: JsonElement): KeyedDoc {
        if (state.keys.contains(key)) return state
        val pos = positionAfter(state.keys, after)
        val keys = state.keys.toMutableList().apply { add(pos, key) }
        val fields = state.fields.toMutableList().apply { add(pos, value) }
        return KeyedDoc(withFields(state.doc, fields), keys)
    }

    private fun delete(state: KeyedDoc, key: String): KeyedDoc {
        val idx = state.keys.indexOf(key)
        if (idx < 0) return state
        val keys = state.keys.toMutableList().apply { removeAt(idx) }
        val fields = state.fields.toMutableList().apply { removeAt(idx) }
        return KeyedDoc(withFields(state.doc, fields), keys)
    }

    private fun move(state: KeyedDoc, key: String, after: String?): KeyedDoc {
        val idx = state.keys.indexOf(key)
        if (idx < 0 || after == key) return state
        val keys = state.keys.toMutableList()
        val fields = state.fields.toMutableList()
        keys.removeAt(idx)
        val value = fields.removeAt(idx)
        val pos = positionAfter(keys, after)
        keys.add(pos, key)
        fields.add(pos, value)
        return KeyedDoc(withFields(state.doc, fields), keys)
    }

    private fun positionAfter(keys: List<String>, after: String?): Int {
        if (after == null) return 0
        val idx = keys.indexOf(after)
        return if (idx >= 0) idx + 1 else keys.size
    }

    private fun withFields(doc: JsonObject, fields: List<JsonElement>): JsonObject =
        JsonObject(doc + (FIELDS to JsonArray(fields)))

    // ── Diffing ────────────────────────────────────────────────────────────────

    /**
     * Ops that turn [base] into [target], plus the keys of [target]'s fields (base keys where a field
     * was matched, fresh keys from [newKey] for added fields).
     */
    fun diff(base: KeyedDoc, target: JsonObject, newKey: () -> String): DiffResult {
        val baseFields = base.fields
        val newFields = fieldsOf(target)
        val match = matchFields(baseFields, newFields)

        val newKeys = ArrayList<String>(newFields.size)
        val inserted = BooleanArray(newFields.size)
        for (j in newFields.indices) {
            val i = match[j]
            if (i >= 0) newKeys.add(base.keys[i]) else { newKeys.add(newKey()); inserted[j] = true }
        }

        // Order: deletes, then inserts and moves, then property changes.
        val ops = mutableListOf<JsonObject>()
        val usedBase = BooleanArray(baseFields.size)
        match.forEach { if (it >= 0) usedBase[it] = true }
        for (i in baseFields.indices) if (!usedBase[i]) ops.add(deleteOp(base.keys[i]))

        // Keep the longest run of matched fields that is already in order; move the rest.
        val matchedNewIdx = newFields.indices.filter { match[it] >= 0 }
        val stable = longestIncreasing(matchedNewIdx.map { match[it] }).map { matchedNewIdx[it] }.toHashSet()
        for (j in newFields.indices) {
            val after = if (j == 0) null else newKeys[j - 1]
            when {
                inserted[j] -> ops.add(insertOp(newKeys[j], after, newFields[j]))
                j !in stable -> ops.add(moveOp(newKeys[j], after))
            }
        }

        val topKeys = LinkedHashSet<String>().apply { addAll(base.doc.keys); addAll(target.keys) }
        topKeys.remove(FIELDS)
        for (k in topKeys) diffValue(listOf(k), base.doc[k], target[k], ops)

        for (j in newFields.indices) {
            val i = match[j]
            if (i >= 0) diffValue(listOf(FIELDS, newKeys[j]), baseFields[i], newFields[j], ops)
        }
        return DiffResult(ops, newKeys)
    }

    private fun diffValue(path: List<String>, a: JsonElement?, b: JsonElement?, out: MutableList<JsonObject>) {
        when {
            b == null -> if (a != null) out.add(unsetOp(path))
            a == null -> out.add(setOp(path, b))
            deepEqual(a, b) -> Unit
            a is JsonObject && b is JsonObject -> {
                val keys = LinkedHashSet<String>().apply { addAll(a.keys); addAll(b.keys) }
                for (k in keys) diffValue(path + k, a[k], b[k], out)
            }
            else -> out.add(setOp(path, b))
        }
    }

    /** For each new field, the index of the base field it corresponds to, or -1 if it was added. */
    fun matchFields(base: List<JsonElement>, target: List<JsonElement>): IntArray {
        val match = IntArray(target.size) { -1 }
        val used = BooleanArray(base.size)

        // 1. Unchanged fields.
        val byContent = HashMap<String, ArrayDeque<Int>>()
        base.forEachIndexed { i, f -> byContent.getOrPut(canonical(f)) { ArrayDeque() }.addLast(i) }
        for (j in target.indices) {
            val queue = byContent[canonical(target[j])] ?: continue
            while (queue.isNotEmpty()) {
                val i = queue.removeFirst()
                if (!used[i]) { match[j] = i; used[i] = true; break }
            }
        }
        // 2. Same field id.
        for (j in target.indices) {
            if (match[j] >= 0) continue
            val id = fieldId(target[j]) ?: continue
            for (i in base.indices) {
                if (!used[i] && fieldId(base[i]) == id) { match[j] = i; used[i] = true; break }
            }
        }
        // 3. Same position (an edit that also changed the id).
        for (j in target.indices) {
            if (match[j] >= 0 || j >= base.size || used[j]) continue
            if (base[j] is JsonObject && target[j] is JsonObject) { match[j] = j; used[j] = true }
        }
        return match
    }

    private fun fieldId(f: JsonElement): String? =
        stringOrNull((f as? JsonObject)?.get("id"))?.takeIf { it.isNotEmpty() }

    /** Indices (into [seq]) of one longest strictly increasing subsequence. */
    private fun longestIncreasing(seq: List<Int>): List<Int> {
        if (seq.isEmpty()) return emptyList()
        val tailIdx = ArrayList<Int>()
        val prev = IntArray(seq.size) { -1 }
        for (i in seq.indices) {
            var lo = 0
            var hi = tailIdx.size
            while (lo < hi) {
                val mid = (lo + hi) ushr 1
                if (seq[tailIdx[mid]] < seq[i]) lo = mid + 1 else hi = mid
            }
            if (lo > 0) prev[i] = tailIdx[lo - 1]
            if (lo == tailIdx.size) tailIdx.add(i) else tailIdx[lo] = i
        }
        val out = ArrayList<Int>()
        var k = tailIdx.last()
        while (k >= 0) { out.add(k); k = prev[k] }
        return out.reversed()
    }

    // ── Merging ────────────────────────────────────────────────────────────────

    /**
     * Rebases [ops] (written against [base]) onto [theirs], a plain config that also descends from [base].
     * Returns [theirs] keyed in [base]'s key space with [ops] applied; on a conflicting property [ops] win.
     */
    fun rebase(base: KeyedDoc, theirs: JsonObject, ops: List<JsonElement>, newKey: () -> String): KeyedDoc {
        val theirsKeyed = KeyedDoc(ensureFields(theirs), diff(base, theirs, newKey).keys)
        return applyOps(theirsKeyed, ops)
    }

    fun ensureFields(doc: JsonObject): JsonObject =
        if (doc[FIELDS] is JsonArray) doc else JsonObject(doc + (FIELDS to JsonArray(emptyList())))

    // ── JSON helpers ───────────────────────────────────────────────────────────

    fun deepEqual(a: JsonElement?, b: JsonElement?): Boolean {
        if (a === b) return true
        if (a == null || b == null) return false
        return when (a) {
            is JsonNull -> b is JsonNull
            is JsonPrimitive -> {
                if (b !is JsonPrimitive || b is JsonNull) return false
                if (a.isString || b.isString) return a.isString == b.isString && a.content == b.content
                val da = a.content.toDoubleOrNull()
                val db = b.content.toDoubleOrNull()
                if (da != null && db != null) da == db else a.content == b.content
            }
            is JsonArray -> b is JsonArray && a.size == b.size && a.indices.all { deepEqual(a[it], b[it]) }
            is JsonObject -> b is JsonObject && a.size == b.size && a.all { (k, v) -> b.containsKey(k) && deepEqual(v, b[k]) }
        }
    }

    /** Order-independent text for content matching. */
    fun canonical(e: JsonElement): String = buildString { writeCanonical(e, this) }

    private fun writeCanonical(e: JsonElement, sb: StringBuilder) {
        when (e) {
            is JsonNull -> sb.append("null")
            is JsonPrimitive -> when {
                e.isString -> sb.append(JsonPrimitive(e.content).toString())
                else -> {
                    val d = e.content.toDoubleOrNull()
                    if (d != null && d == Math.rint(d) && Math.abs(d) < 1e15) sb.append(d.toLong()) else sb.append(e.content)
                }
            }
            is JsonArray -> {
                sb.append('[')
                e.forEachIndexed { i, v -> if (i > 0) sb.append(','); writeCanonical(v, sb) }
                sb.append(']')
            }
            is JsonObject -> {
                sb.append('{')
                e.keys.sorted().forEachIndexed { i, k ->
                    if (i > 0) sb.append(',')
                    sb.append(JsonPrimitive(k).toString()).append(':')
                    writeCanonical(e.getValue(k), sb)
                }
                sb.append('}')
            }
        }
    }

    private fun stringOrNull(e: JsonElement?): String? = (e as? JsonPrimitive)?.takeIf { it.isString }?.content

    private fun pathArray(path: List<String>) = JsonArray(path.map { JsonPrimitive(it) })

    fun setOp(path: List<String>, value: JsonElement) = buildJsonObject {
        put("op", "set"); put("path", pathArray(path)); put("value", value)
    }

    fun unsetOp(path: List<String>) = buildJsonObject { put("op", "unset"); put("path", pathArray(path)) }

    fun insertOp(key: String, after: String?, value: JsonElement) = buildJsonObject {
        put("op", "insert"); put("key", key); put("after", after?.let { JsonPrimitive(it) } ?: JsonNull); put("value", value)
    }

    fun deleteOp(key: String) = buildJsonObject { put("op", "delete"); put("key", key) }

    fun moveOp(key: String, after: String?) = buildJsonObject {
        put("op", "move"); put("key", key); put("after", after?.let { JsonPrimitive(it) } ?: JsonNull)
    }
}
