package com.obsidianscout.db

import com.obsidianscout.config.DatabaseConfig
import com.zaxxer.hikari.HikariConfig
import com.zaxxer.hikari.HikariDataSource
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.transactions.transaction
import java.nio.file.Files
import java.nio.file.Paths
import java.sql.DriverManager
import java.util.UUID

object DatabaseFactory {
    private val uuidMigratedTables = listOf(
        "users", "scouting_configs", "pit_scouting_configs",
        "qualitative_scouting_configs", "scouting_entries",
        "pit_scouting_entries", "qualitative_scouting_entries",
        "app_settings", "api_events", "api_teams", "api_matches",
        "scouting_alliances", "alliance_memberships",
        "epa_opr_history_cache", "password_reset_tokens",
        "alliance_selections", "banners", "chat_messages",
        "user_chat_last_read", "push_subscriptions"
    )

    fun init(config: DatabaseConfig) {
        ensureJdbcDriverLoaded(config.type)

        if (config.type.lowercase() == "postgres") {
            ensurePostgresDatabaseExists(config)
        }

        val hikariConfig = HikariConfig().apply {
            val type = config.type.lowercase()
            val jdbcUrl = when (type) {
                "postgres" -> buildPostgresUrl(config)
                else -> buildSqliteUrl(config)
            }
            this.jdbcUrl = jdbcUrl
            driverClassName = if (type == "postgres") {
                "org.postgresql.Driver"
            } else {
                "org.sqlite.JDBC"
            }
            if (type == "postgres") {
                maximumPoolSize = 20
                minimumIdle = 2
                isAutoCommit = true
                username = config.postgres.user
                password = config.postgres.password
                transactionIsolation = "TRANSACTION_READ_COMMITTED"
            } else {
                maximumPoolSize = 16
                minimumIdle = 2
                isAutoCommit = true
            }
            connectionTimeout = 10_000  // fail fast after 10s instead of the 30s default
            leakDetectionThreshold = 5000L
        }

        val dataSource = HikariDataSource(hikariConfig)
        Database.connect(dataSource)

        // Run the INT->UUID migration if the database still has the old schema
        migrateIntToUuidIfNeeded(config)

        transaction {
            SchemaUtils.createMissingTablesAndColumns(
                Users,
                ScoutingConfigs,
                PitScoutingConfigs,
                QualitativeScoutingConfigs,
                ScoutingEntries,
                PitScoutingEntries,
                QualitativeScoutingEntries,
                AppSettings,
                ApiEvents,
                ApiTeams,
                ApiMatches,
                ScoutingAlliances,
                AllianceMemberships,
                EpaOprHistoryCache,
                PasswordResetTokens,
                AllianceSelections,
                Banners,
                ChatMessages,
                UserChatLastRead,
                PushSubscriptions
            )
        }
    }

    /**
     * Detects whether the database still uses the old INTEGER primary-key schema and
     * migrates all data to UUID primary keys if so.
     *
     * Strategy:
     *   1. Check if the `users` table exists AND its `id` column is numeric (INTEGER/BIGINT/int4/serial…).
     *   2. If yes, rename every affected table to `old_<name>`.
     *   3. Create the new UUID-keyed tables via Exposed.
     *   4. Copy data row-by-row, minting new server-side UUIDs (UUID.randomUUID()) and
     *      maintaining old-id → new-uuid maps to preserve FK relationships.
     *   5. Drop the `old_` tables.
     *
     * UUIDs are always generated by the JVM (UUID.randomUUID()), never by a database
     * function such as gen_random_uuid(), so they are safe for multi-master replication.
     */
    private fun migrateIntToUuidIfNeeded(config: DatabaseConfig) {
        val isPostgres = config.type.lowercase() == "postgres"
        ensureJdbcDriverLoaded(config.type)
        val jdbcUrl = if (isPostgres) buildPostgresUrl(config) else buildSqliteUrl(config)
        val user = if (isPostgres) config.postgres.user else null
        val pass = if (isPostgres) config.postgres.password else null

        val conn = if (user != null) {
            DriverManager.getConnection(jdbcUrl, user, pass)
        } else {
            DriverManager.getConnection(jdbcUrl)
        }

        conn.use { c ->
            c.autoCommit = false
            try {
                // ── 1. Detect old schema ────────────────────────────────────────
                val needsMigration = c.createStatement().use { stmt ->
                    val rs = stmt.executeQuery(
                        if (isPostgres) {
                            """
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name = 'users'
                              AND column_name = 'id'
                              AND (data_type ILIKE '%int%' OR data_type ILIKE 'serial%' OR udt_name ILIKE '%int%')
                            """.trimIndent()
                        } else {
                            // SQLite: check column info; id type is INTEGER
                            "PRAGMA table_info(users)"
                        }
                    )
                    if (isPostgres) {
                        rs.next()
                    } else {
                        var found = false
                        while (rs.next()) {
                            if (rs.getString("name") == "id" && rs.getString("type").contains("INT", ignoreCase = true)) {
                                found = true
                                break
                            }
                        }
                        found
                    }
                }

                val hasInterruptedMigration = tableExists(c, "old_users", isPostgres)

                if (!needsMigration && !hasInterruptedMigration) {
                    if (isPostgres) {
                        dropOldPostgresConstraintsAndIndexes(c, uuidMigratedTables)
                        c.commit()
                    }
                    return  // Already on UUID schema
                }

                if (hasInterruptedMigration) {
                    println("[DB Migration] Found interrupted INT→UUID migration. Rebuilding UUID tables from old_* tables...")
                    dropTargetTablesForMigrationResume(c, uuidMigratedTables, isPostgres)
                    if (isPostgres) {
                        dropOldPostgresConstraintsAndIndexes(c, uuidMigratedTables)
                    }
                    c.commit()
                } else {
                    println("[DB Migration] INT→UUID migration required. Starting migration...")
                }

                // ── 2. Rename old tables ────────────────────────────────────────
                val tables = uuidMigratedTables

                if (!hasInterruptedMigration) {
                    c.createStatement().use { stmt ->
                        for (table in tables) {
                            if (tableExists(c, table, isPostgres)) {
                                println("[DB Migration] Renaming $table -> old_$table")
                                stmt.execute("ALTER TABLE ${quoteIdent(table)} RENAME TO ${quoteIdent("old_$table")}")
                            }
                        }
                    }
                    if (isPostgres) {
                        dropOldPostgresConstraintsAndIndexes(c, tables)
                    }
                    c.commit()
                }

                // ── 3. Create new UUID tables via Exposed ───────────────────────
                transaction {
                    SchemaUtils.createMissingTablesAndColumns(
                        Users,
                        ScoutingConfigs,
                        PitScoutingConfigs,
                        QualitativeScoutingConfigs,
                        ScoutingEntries,
                        PitScoutingEntries,
                        QualitativeScoutingEntries,
                        AppSettings,
                        ApiEvents,
                        ApiTeams,
                        ApiMatches,
                        ScoutingAlliances,
                        AllianceMemberships,
                        EpaOprHistoryCache,
                        PasswordResetTokens,
                        AllianceSelections,
                        Banners,
                        ChatMessages,
                        UserChatLastRead,
                        PushSubscriptions
                    )
                }

                // ── 4. Copy data, minting UUIDs on the server ───────────────────
                //
                //  All UUIDs are generated via UUID.randomUUID() — never gen_random_uuid()
                //  so they are safe for multi-master pgEdge replication.
                //
                //  Approach: build old-int-id → new-UUID maps for tables that have FKs
                //  pointing to them, then use those maps when copying the FK columns.

                // --- users ---
                val userIdMap = mutableMapOf<Int, UUID>()   // old int id -> new UUID
                c.createStatement().executeQuery(
                    "SELECT id, username, team_number, password_hash, role, created_at, email, profile_picture, notification_preference, tour_progress FROM \"old_users\""
                ).use { rs ->
                    while (rs.next()) {
                        val oldId = rs.getInt("id")
                        val newUuid = UUID.randomUUID()
                        userIdMap[oldId] = newUuid
                        c.prepareStatement(
                            "INSERT INTO users (id, username, team_number, password_hash, role, created_at, email, profile_picture, notification_preference, tour_progress) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
                        ).use { ps ->
                            setUuidParam(ps, 1, newUuid, isPostgres)
                            ps.setString(2, rs.getString("username"))
                            ps.setInt(3, rs.getInt("team_number"))
                            ps.setString(4, rs.getString("password_hash"))
                            ps.setString(5, rs.getString("role"))
                            setTimestampParam(ps, 6, rs.getString("created_at"), isPostgres)
                            ps.setString(7, rs.getString("email"))
                            ps.setString(8, rs.getString("profile_picture"))
                            ps.setString(9, rs.getString("notification_preference") ?: "all")
                            ps.setString(10, rs.getString("tour_progress"))
                            ps.executeUpdate()
                        }
                    }
                }
                c.commit()
                println("[DB Migration] Migrated ${userIdMap.size} users")

                // --- scouting_alliances ---
                val allianceIdMap = mutableMapOf<Int, UUID>()
                tableExistsOld(c, "old_scouting_alliances", isPostgres) {
                    c.createStatement().executeQuery(
                        "SELECT id, name, owner_team_number, event_key, notes, created_at, updated_at, match_config_json, pit_config_json, qualitative_config_json, year, event_code FROM \"old_scouting_alliances\""
                    ).use { rs ->
                        while (rs.next()) {
                            val oldId = rs.getInt("id")
                            val newUuid = UUID.randomUUID()
                            allianceIdMap[oldId] = newUuid
                            c.prepareStatement(
                                "INSERT INTO scouting_alliances (id, name, owner_team_number, event_key, notes, created_at, updated_at, match_config_json, pit_config_json, qualitative_config_json, year, event_code) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
                            ).use { ps ->
                                setUuidParam(ps, 1, newUuid, isPostgres)
                                ps.setString(2, rs.getString("name"))
                                ps.setInt(3, rs.getInt("owner_team_number"))
                                ps.setString(4, rs.getString("event_key"))
                                ps.setString(5, rs.getString("notes"))
                                setTimestampParam(ps, 6, rs.getString("created_at"), isPostgres)
                                setTimestampParam(ps, 7, rs.getString("updated_at"), isPostgres)
                                ps.setString(8, rs.getString("match_config_json"))
                                ps.setString(9, rs.getString("pit_config_json"))
                                ps.setString(10, rs.getString("qualitative_config_json"))
                                val year = rs.getObject("year")
                                if (year != null) ps.setInt(11, rs.getInt("year")) else ps.setNull(11, java.sql.Types.INTEGER)
                                ps.setString(12, rs.getString("event_code"))
                                ps.executeUpdate()
                            }
                        }
                    }
                }
                c.commit()
                println("[DB Migration] Migrated ${allianceIdMap.size} alliances")

                // --- scouting_entries ---
                copyScoutingTable(c, "old_scouting_entries", "scouting_entries", userIdMap, isPostgres,
                    extraColumns = listOf("match_key", "match_number", "is_prescout", "has_discrepancy", "conflicting_teams"),
                    insertBlock = { ps, rs, submitterId ->
                        setUuidParam(ps, 1, UUID.randomUUID(), isPostgres)
                        ps.setInt(2, rs.getInt("owner_team_number"))
                        val ttn = rs.getObject("target_team_number")
                        if (ttn != null) ps.setInt(3, rs.getInt("target_team_number")) else ps.setNull(3, java.sql.Types.INTEGER)
                        ps.setString(4, rs.getString("event_key"))
                        ps.setString(5, rs.getString("match_key"))
                        val mn = rs.getObject("match_number")
                        if (mn != null) ps.setInt(6, rs.getInt("match_number")) else ps.setNull(6, java.sql.Types.INTEGER)
                        ps.setString(7, rs.getString("data_json"))
                        setUuidParam(ps, 8, submitterId, isPostgres)
                        setTimestampParam(ps, 9, rs.getString("created_at"), isPostgres)
                        ps.setBoolean(10, rs.getBoolean("is_prescout"))
                        ps.setBoolean(11, rs.getBoolean("has_discrepancy"))
                        ps.setString(12, rs.getString("conflicting_teams") ?: "")
                    },
                    sql = "INSERT INTO scouting_entries (id, owner_team_number, target_team_number, event_key, match_key, match_number, data_json, submitted_by_user_id, created_at, is_prescout, has_discrepancy, conflicting_teams) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
                )
                c.commit()

                // --- pit_scouting_entries ---
                copyPitTable(c, "old_pit_scouting_entries", "pit_scouting_entries", userIdMap, isPostgres)
                c.commit()

                // --- qualitative_scouting_entries ---
                copyQualTable(c, "old_qualitative_scouting_entries", "qualitative_scouting_entries", userIdMap, isPostgres)
                c.commit()

                // --- scouting_configs ---
                copyConfigTable(c, "old_scouting_configs", "scouting_configs", isPostgres)
                copyConfigTable(c, "old_pit_scouting_configs", "pit_scouting_configs", isPostgres)
                copyConfigTable(c, "old_qualitative_scouting_configs", "qualitative_scouting_configs", isPostgres)
                c.commit()

                // --- app_settings ---
                tableExistsOld(c, "old_app_settings", isPostgres) {
                    c.createStatement().executeQuery("SELECT team_number, settings_json, updated_at FROM \"old_app_settings\"").use { rs ->
                        while (rs.next()) {
                            c.prepareStatement("INSERT INTO app_settings (id, team_number, settings_json, updated_at) VALUES (?, ?, ?, ?)").use { ps ->
                                setUuidParam(ps, 1, UUID.randomUUID(), isPostgres)
                                ps.setInt(2, rs.getInt("team_number"))
                                ps.setString(3, rs.getString("settings_json"))
                                setTimestampParam(ps, 4, rs.getString("updated_at"), isPostgres)
                                ps.executeUpdate()
                            }
                        }
                    }
                }

                // --- api_events ---
                tableExistsOld(c, "old_api_events", isPostgres) {
                    c.createStatement().executeQuery("SELECT event_key, year, event_code, name, start_date, end_date, timezone, data_json, updated_at FROM \"old_api_events\"").use { rs ->
                        while (rs.next()) {
                            c.prepareStatement("INSERT INTO api_events (id, event_key, year, event_code, name, start_date, end_date, timezone, data_json, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").use { ps ->
                                setUuidParam(ps, 1, UUID.randomUUID(), isPostgres)
                                ps.setString(2, rs.getString("event_key"))
                                ps.setInt(3, rs.getInt("year"))
                                ps.setString(4, rs.getString("event_code"))
                                ps.setString(5, rs.getString("name"))
                                ps.setString(6, rs.getString("start_date"))
                                ps.setString(7, rs.getString("end_date"))
                                ps.setString(8, rs.getString("timezone"))
                                ps.setString(9, rs.getString("data_json"))
                                setTimestampParam(ps, 10, rs.getString("updated_at"), isPostgres)
                                ps.executeUpdate()
                            }
                        }
                    }
                }

                // --- api_teams ---
                tableExistsOld(c, "old_api_teams", isPostgres) {
                    c.createStatement().executeQuery("SELECT event_key, team_key, team_number, name, nickname, city, state, country, opr, epa, data_json, updated_at FROM \"old_api_teams\"").use { rs ->
                        while (rs.next()) {
                            c.prepareStatement("INSERT INTO api_teams (id, event_key, team_key, team_number, name, nickname, city, state, country, opr, epa, data_json, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").use { ps ->
                                setUuidParam(ps, 1, UUID.randomUUID(), isPostgres)
                                ps.setString(2, rs.getString("event_key"))
                                ps.setString(3, rs.getString("team_key"))
                                ps.setInt(4, rs.getInt("team_number"))
                                ps.setString(5, rs.getString("name"))
                                ps.setString(6, rs.getString("nickname"))
                                ps.setString(7, rs.getString("city"))
                                ps.setString(8, rs.getString("state"))
                                ps.setString(9, rs.getString("country"))
                                val opr = rs.getObject("opr"); if (opr != null) ps.setDouble(10, rs.getDouble("opr")) else ps.setNull(10, java.sql.Types.DOUBLE)
                                val epa = rs.getObject("epa"); if (epa != null) ps.setDouble(11, rs.getDouble("epa")) else ps.setNull(11, java.sql.Types.DOUBLE)
                                ps.setString(12, rs.getString("data_json"))
                                setTimestampParam(ps, 13, rs.getString("updated_at"), isPostgres)
                                ps.executeUpdate()
                            }
                        }
                    }
                }

                // --- api_matches ---
                tableExistsOld(c, "old_api_matches", isPostgres) {
                    c.createStatement().executeQuery("SELECT match_key, event_key, comp_level, set_number, match_number, scheduled_time, actual_time, red_teams, blue_teams, data_json, updated_at FROM \"old_api_matches\"").use { rs ->
                        while (rs.next()) {
                            c.prepareStatement("INSERT INTO api_matches (id, match_key, event_key, comp_level, set_number, match_number, scheduled_time, actual_time, red_teams, blue_teams, data_json, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").use { ps ->
                                setUuidParam(ps, 1, UUID.randomUUID(), isPostgres)
                                ps.setString(2, rs.getString("match_key"))
                                ps.setString(3, rs.getString("event_key"))
                                ps.setString(4, rs.getString("comp_level"))
                                val sn = rs.getObject("set_number"); if (sn != null) ps.setInt(5, rs.getInt("set_number")) else ps.setNull(5, java.sql.Types.INTEGER)
                                val mn = rs.getObject("match_number"); if (mn != null) ps.setInt(6, rs.getInt("match_number")) else ps.setNull(6, java.sql.Types.INTEGER)
                                val st = rs.getObject("scheduled_time"); if (st != null) ps.setLong(7, rs.getLong("scheduled_time")) else ps.setNull(7, java.sql.Types.BIGINT)
                                val at = rs.getObject("actual_time"); if (at != null) ps.setLong(8, rs.getLong("actual_time")) else ps.setNull(8, java.sql.Types.BIGINT)
                                ps.setString(9, rs.getString("red_teams"))
                                ps.setString(10, rs.getString("blue_teams"))
                                ps.setString(11, rs.getString("data_json"))
                                setTimestampParam(ps, 12, rs.getString("updated_at"), isPostgres)
                                ps.executeUpdate()
                            }
                        }
                    }
                }

                // --- alliance_memberships ---
                tableExistsOld(c, "old_alliance_memberships", isPostgres) {
                    c.createStatement().executeQuery("SELECT alliance_id, team_number, status, invited_at, responded_at, disabled, active FROM \"old_alliance_memberships\"").use { rs ->
                        while (rs.next()) {
                            val oldAllianceId = rs.getInt("alliance_id")
                            val newAllianceUuid = allianceIdMap[oldAllianceId] ?: UUID.randomUUID()
                            c.prepareStatement("INSERT INTO alliance_memberships (id, alliance_id, team_number, status, invited_at, responded_at, disabled, active) VALUES (?, ?, ?, ?, ?, ?, ?, ?)").use { ps ->
                                setUuidParam(ps, 1, UUID.randomUUID(), isPostgres)
                                setUuidParam(ps, 2, newAllianceUuid, isPostgres)
                                ps.setInt(3, rs.getInt("team_number"))
                                ps.setString(4, rs.getString("status"))
                                setTimestampParam(ps, 5, rs.getString("invited_at"), isPostgres)
                                setTimestampParam(ps, 6, rs.getString("responded_at"), isPostgres, nullable = true)
                                ps.setBoolean(7, rs.getBoolean("disabled"))
                                ps.setBoolean(8, rs.getBoolean("active"))
                                ps.executeUpdate()
                            }
                        }
                    }
                }

                // --- epa_opr_history_cache ---
                tableExistsOld(c, "old_epa_opr_history_cache", isPostgres) {
                    c.createStatement().executeQuery("SELECT event_key, oprs_json, epa_history_json, updated_at FROM \"old_epa_opr_history_cache\"").use { rs ->
                        while (rs.next()) {
                            c.prepareStatement("INSERT INTO epa_opr_history_cache (id, event_key, oprs_json, epa_history_json, updated_at) VALUES (?, ?, ?, ?, ?)").use { ps ->
                                setUuidParam(ps, 1, UUID.randomUUID(), isPostgres)
                                ps.setString(2, rs.getString("event_key"))
                                ps.setString(3, rs.getString("oprs_json"))
                                ps.setString(4, rs.getString("epa_history_json"))
                                setTimestampParam(ps, 5, rs.getString("updated_at"), isPostgres)
                                ps.executeUpdate()
                            }
                        }
                    }
                }

                // --- password_reset_tokens ---
                tableExistsOld(c, "old_password_reset_tokens", isPostgres) {
                    c.createStatement().executeQuery("SELECT user_id, email, token, expires_at, used FROM \"old_password_reset_tokens\"").use { rs ->
                        while (rs.next()) {
                            val oldUserId = rs.getObject("user_id")?.let { rs.getInt("user_id") }
                            val newUserUuid = oldUserId?.let { userIdMap[it]?.toString() }
                            c.prepareStatement("INSERT INTO password_reset_tokens (id, user_id, email, token, expires_at, used) VALUES (?, ?, ?, ?, ?, ?)").use { ps ->
                                setUuidParam(ps, 1, UUID.randomUUID(), isPostgres)
                                if (newUserUuid != null) setUuidParam(ps, 2, newUserUuid, isPostgres) else ps.setNull(2, if (isPostgres) java.sql.Types.OTHER else java.sql.Types.VARCHAR)
                                ps.setString(3, rs.getString("email"))
                                ps.setString(4, rs.getString("token"))
                                setTimestampParam(ps, 5, rs.getString("expires_at"), isPostgres)
                                ps.setBoolean(6, rs.getBoolean("used"))
                                ps.executeUpdate()
                            }
                        }
                    }
                }

                // --- alliance_selections ---
                tableExistsOld(c, "old_alliance_selections", isPostgres) {
                    c.createStatement().executeQuery("SELECT owner_key, event_key, selection_json, updated_at FROM \"old_alliance_selections\"").use { rs ->
                        while (rs.next()) {
                            c.prepareStatement("INSERT INTO alliance_selections (id, owner_key, event_key, selection_json, updated_at) VALUES (?, ?, ?, ?, ?)").use { ps ->
                                setUuidParam(ps, 1, UUID.randomUUID(), isPostgres)
                                ps.setString(2, rs.getString("owner_key"))
                                ps.setString(3, rs.getString("event_key"))
                                ps.setString(4, rs.getString("selection_json"))
                                setTimestampParam(ps, 5, rs.getString("updated_at"), isPostgres)
                                ps.executeUpdate()
                            }
                        }
                    }
                }

                // --- banners ---
                tableExistsOld(c, "old_banners", isPostgres) {
                    c.createStatement().executeQuery("SELECT team_number, message, banner_type, is_dismissible, is_expandable, expandable_message, is_active, created_at, updated_at FROM \"old_banners\"").use { rs ->
                        while (rs.next()) {
                            c.prepareStatement("INSERT INTO banners (id, team_number, message, banner_type, is_dismissible, is_expandable, expandable_message, is_active, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").use { ps ->
                                setUuidParam(ps, 1, UUID.randomUUID(), isPostgres)
                                ps.setInt(2, rs.getInt("team_number"))
                                ps.setString(3, rs.getString("message"))
                                ps.setString(4, rs.getString("banner_type") ?: "info")
                                ps.setBoolean(5, rs.getBoolean("is_dismissible"))
                                ps.setBoolean(6, rs.getBoolean("is_expandable"))
                                ps.setString(7, rs.getString("expandable_message") ?: "")
                                ps.setBoolean(8, rs.getBoolean("is_active"))
                                setTimestampParam(ps, 9, rs.getString("created_at"), isPostgres)
                                setTimestampParam(ps, 10, rs.getString("updated_at"), isPostgres)
                                ps.executeUpdate()
                            }
                        }
                    }
                }

                // --- chat_messages ---
                tableExistsOld(c, "old_chat_messages", isPostgres) {
                    c.createStatement().executeQuery("SELECT team_number, group_name, user_id, username, content, created_at, reactions_json FROM \"old_chat_messages\"").use { rs ->
                        while (rs.next()) {
                            val oldUserId = rs.getInt("user_id")
                            val newUserUuid = userIdMap[oldUserId]?.toString() ?: UUID.randomUUID().toString()
                            c.prepareStatement("INSERT INTO chat_messages (id, team_number, group_name, user_id, username, content, created_at, reactions_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?)").use { ps ->
                                setUuidParam(ps, 1, UUID.randomUUID(), isPostgres)
                                ps.setInt(2, rs.getInt("team_number"))
                                ps.setString(3, rs.getString("group_name"))
                                setUuidParam(ps, 4, newUserUuid, isPostgres)
                                ps.setString(5, rs.getString("username"))
                                ps.setString(6, rs.getString("content"))
                                setTimestampParam(ps, 7, rs.getString("created_at"), isPostgres)
                                ps.setString(8, rs.getString("reactions_json") ?: "{}")
                                ps.executeUpdate()
                            }
                        }
                    }
                }

                // --- user_chat_last_read ---
                tableExistsOld(c, "old_user_chat_last_read", isPostgres) {
                    c.createStatement().executeQuery("SELECT user_id, group_name, last_read_at FROM \"old_user_chat_last_read\"").use query@ { rs ->
                        while (rs.next()) {
                            val oldUserId = rs.getInt("user_id")
                            val newUserUuid = userIdMap[oldUserId]?.toString() ?: return@query
                            c.prepareStatement("INSERT INTO user_chat_last_read (id, user_id, group_name, last_read_at) VALUES (?, ?, ?, ?)").use { ps ->
                                setUuidParam(ps, 1, UUID.randomUUID(), isPostgres)
                                setUuidParam(ps, 2, newUserUuid, isPostgres)
                                ps.setString(3, rs.getString("group_name"))
                                setTimestampParam(ps, 4, rs.getString("last_read_at"), isPostgres)
                                ps.executeUpdate()
                            }
                        }
                    }
                }

                // --- push_subscriptions ---
                tableExistsOld(c, "old_push_subscriptions", isPostgres) {
                    c.createStatement().executeQuery("SELECT user_id, endpoint, p256dh, auth, created_at FROM \"old_push_subscriptions\"").use query@ { rs ->
                        while (rs.next()) {
                            val oldUserId = rs.getInt("user_id")
                            val newUserUuid = userIdMap[oldUserId]?.toString() ?: return@query
                            c.prepareStatement("INSERT INTO push_subscriptions (id, user_id, endpoint, p256dh, auth, created_at) VALUES (?, ?, ?, ?, ?, ?)").use { ps ->
                                setUuidParam(ps, 1, UUID.randomUUID(), isPostgres)
                                setUuidParam(ps, 2, newUserUuid, isPostgres)
                                ps.setString(3, rs.getString("endpoint"))
                                ps.setString(4, rs.getString("p256dh"))
                                ps.setString(5, rs.getString("auth"))
                                setTimestampParam(ps, 6, rs.getString("created_at"), isPostgres)
                                ps.executeUpdate()
                            }
                        }
                    }
                }

                c.commit()

                // ── 5. Drop old tables ──────────────────────────────────────────
                c.createStatement().use { stmt ->
                    for (table in tables.reversed()) {
                        try {
                            stmt.execute("DROP TABLE IF EXISTS \"old_$table\"")
                        } catch (_: Exception) {}
                    }
                }
                c.commit()

                println("[DB Migration] INT→UUID migration complete!")

            } catch (e: Exception) {
                c.rollback()
                println("[DB Migration] ERROR during migration: ${e.message}")
                e.printStackTrace()
                throw e
            }
        }
    }

    // ── Helpers ─────────────────────────────────────────────────────────────────

    private fun quoteIdent(identifier: String): String {
        return "\"" + identifier.replace("\"", "\"\"") + "\""
    }

    private fun setUuidParam(ps: java.sql.PreparedStatement, index: Int, uuid: UUID, isPostgres: Boolean) {
        if (isPostgres) {
            ps.setObject(index, uuid)
        } else {
            ps.setString(index, uuid.toString())
        }
    }

    private fun setUuidParam(ps: java.sql.PreparedStatement, index: Int, uuidText: String, isPostgres: Boolean) {
        if (isPostgres) {
            ps.setObject(index, UUID.fromString(uuidText))
        } else {
            ps.setString(index, uuidText)
        }
    }

    private fun setTimestampParam(
        ps: java.sql.PreparedStatement,
        index: Int,
        value: String?,
        isPostgres: Boolean,
        nullable: Boolean = false
    ) {
        val text = value?.trim()?.takeIf { it.isNotEmpty() }
        if (text == null && nullable) {
            ps.setNull(index, if (isPostgres) java.sql.Types.TIMESTAMP else java.sql.Types.VARCHAR)
            return
        }
        val fallback = java.time.Instant.now().toString()
        if (!isPostgres) {
            ps.setString(index, text ?: fallback)
            return
        }

        val timestamp = parseTimestamp(text ?: fallback)
            ?: java.sql.Timestamp.from(java.time.Instant.now())
        ps.setTimestamp(index, timestamp)
    }

    private fun parseTimestamp(value: String): java.sql.Timestamp? {
        val trimmed = value.trim()
        runCatching {
            return java.sql.Timestamp.from(java.time.Instant.parse(trimmed))
        }
        runCatching {
            return java.sql.Timestamp.valueOf(trimmed.replace('T', ' ').removeSuffix("Z"))
        }
        runCatching {
            val normalized = trimmed.replace(' ', 'T').removeSuffix("Z")
            return java.sql.Timestamp.valueOf(java.time.LocalDateTime.parse(normalized))
        }
        return null
    }

    private fun tableExists(conn: java.sql.Connection, tableName: String, isPostgres: Boolean): Boolean {
        return if (isPostgres) {
            conn.prepareStatement(
                "SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = ?"
            ).use { ps ->
                ps.setString(1, tableName)
                ps.executeQuery().use { it.next() }
            }
        } else {
            conn.prepareStatement(
                "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?"
            ).use { ps ->
                ps.setString(1, tableName)
                ps.executeQuery().use { it.next() }
            }
        }
    }

    private fun dropTargetTablesForMigrationResume(conn: java.sql.Connection, tables: List<String>, isPostgres: Boolean) {
        conn.createStatement().use { stmt ->
            for (table in tables.reversed()) {
                if (tableExists(conn, table, isPostgres)) {
                    val cascade = if (isPostgres) " CASCADE" else ""
                    stmt.execute("DROP TABLE IF EXISTS ${quoteIdent(table)}$cascade")
                }
            }
        }
    }

    private fun dropOldPostgresConstraintsAndIndexes(conn: java.sql.Connection, tables: List<String>) {
        for (table in tables) {
            val oldTable = "old_$table"
            if (!tableExists(conn, oldTable, isPostgres = true)) continue

            val constraints = mutableListOf<String>()
            conn.prepareStatement(
                """
                SELECT conname
                FROM pg_constraint
                WHERE conrelid = to_regclass(?)
                  AND contype <> 'n'
                """.trimIndent()
            ).use { ps ->
                ps.setString(1, oldTable)
                ps.executeQuery().use { rs ->
                    while (rs.next()) {
                        constraints.add(rs.getString("conname"))
                    }
                }
            }

            conn.createStatement().use { stmt ->
                for (constraint in constraints) {
                    stmt.execute(
                        "ALTER TABLE ${quoteIdent(oldTable)} DROP CONSTRAINT IF EXISTS ${quoteIdent(constraint)} CASCADE"
                    )
                }
            }

            val indexes = mutableListOf<String>()
            conn.prepareStatement(
                """
                SELECT indexname
                FROM pg_indexes
                WHERE schemaname = current_schema()
                  AND tablename = ?
                  AND indexname NOT IN (
                      SELECT c.relname
                      FROM pg_constraint con
                      JOIN pg_class c ON c.oid = con.conindid
                      WHERE con.conrelid = to_regclass(?)
                  )
                """.trimIndent()
            ).use { ps ->
                ps.setString(1, oldTable)
                ps.setString(2, oldTable)
                ps.executeQuery().use { rs ->
                    while (rs.next()) {
                        indexes.add(rs.getString("indexname"))
                    }
                }
            }

            conn.createStatement().use { stmt ->
                for (index in indexes) {
                    stmt.execute("DROP INDEX IF EXISTS ${quoteIdent(index)}")
                }
            }
        }
    }

    private fun tableExistsOld(conn: java.sql.Connection, tableName: String, isPostgres: Boolean, block: () -> Unit) {
        if (tableExists(conn, tableName, isPostgres)) block()
    }

    private fun copyScoutingTable(
        c: java.sql.Connection,
        srcTable: String,
        dstTable: String,
        userIdMap: Map<Int, UUID>,
        isPostgres: Boolean,
        extraColumns: List<String>,
        insertBlock: (java.sql.PreparedStatement, java.sql.ResultSet, String) -> Unit,
        sql: String
    ) {
        tableExistsOld(c, srcTable, isPostgres) {
            try {
                c.createStatement().executeQuery("SELECT * FROM \"$srcTable\"").use query@ { rs ->
                    var count = 0
                    while (rs.next()) {
                        val oldUserId = rs.getInt("submitted_by_user_id")
                        val newUserUuid = userIdMap[oldUserId]?.toString() ?: UUID.randomUUID().toString()
                        c.prepareStatement(sql).use { ps ->
                            insertBlock(ps, rs, newUserUuid)
                            ps.executeUpdate()
                        }
                        count++
                    }
                    println("[DB Migration] Migrated $count rows from $srcTable into $dstTable")
                    if (extraColumns.isNotEmpty()) {
                        println("[DB Migration] Extra columns preserved for $dstTable: ${extraColumns.joinToString(", ")}")
                    }
                }
            } catch (_: Exception) {}
        }
    }

    private fun copyPitTable(c: java.sql.Connection, srcTable: String, dstTable: String, userIdMap: Map<Int, UUID>, isPostgres: Boolean) {
        try {
            tableExistsOld(c, srcTable, isPostgres) {
                c.createStatement().executeQuery("SELECT * FROM \"$srcTable\"").use { rs ->
                    var count = 0
                    while (rs.next()) {
                        val oldUserId = rs.getInt("submitted_by_user_id")
                        val newUserUuid = userIdMap[oldUserId]?.toString() ?: UUID.randomUUID().toString()
                        c.prepareStatement("INSERT INTO $dstTable (id, owner_team_number, target_team_number, event_key, data_json, submitted_by_user_id, created_at, is_prescout, has_discrepancy, conflicting_teams) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").use { ps ->
                            setUuidParam(ps, 1, UUID.randomUUID(), isPostgres)
                            ps.setInt(2, rs.getInt("owner_team_number"))
                            val ttn = rs.getObject("target_team_number")
                            if (ttn != null) ps.setInt(3, rs.getInt("target_team_number")) else ps.setNull(3, java.sql.Types.INTEGER)
                            ps.setString(4, rs.getString("event_key"))
                            ps.setString(5, rs.getString("data_json"))
                            setUuidParam(ps, 6, newUserUuid, isPostgres)
                            setTimestampParam(ps, 7, rs.getString("created_at"), isPostgres)
                            ps.setBoolean(8, rs.getBoolean("is_prescout"))
                            ps.setBoolean(9, rs.getBoolean("has_discrepancy"))
                            ps.setString(10, rs.getString("conflicting_teams") ?: "")
                            ps.executeUpdate()
                        }
                        count++
                    }
                    println("[DB Migration] Migrated $count rows from $srcTable")
                }
            }
        } catch (_: Exception) {}
    }

    private fun copyQualTable(c: java.sql.Connection, srcTable: String, dstTable: String, userIdMap: Map<Int, UUID>, isPostgres: Boolean) {
        try {
            tableExistsOld(c, srcTable, isPostgres) {
                c.createStatement().executeQuery("SELECT * FROM \"$srcTable\"").use { rs ->
                    var count = 0
                    while (rs.next()) {
                        val oldUserId = rs.getInt("submitted_by_user_id")
                        val newUserUuid = userIdMap[oldUserId]?.toString() ?: UUID.randomUUID().toString()
                        c.prepareStatement("INSERT INTO $dstTable (id, owner_team_number, target_team_number, event_key, match_key, match_number, data_json, submitted_by_user_id, created_at, is_prescout, has_discrepancy, conflicting_teams) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").use { ps ->
                            setUuidParam(ps, 1, UUID.randomUUID(), isPostgres)
                            ps.setInt(2, rs.getInt("owner_team_number"))
                            val ttn = rs.getObject("target_team_number")
                            if (ttn != null) ps.setInt(3, rs.getInt("target_team_number")) else ps.setNull(3, java.sql.Types.INTEGER)
                            ps.setString(4, rs.getString("event_key"))
                            ps.setString(5, rs.getString("match_key"))
                            val mn = rs.getObject("match_number")
                            if (mn != null) ps.setInt(6, rs.getInt("match_number")) else ps.setNull(6, java.sql.Types.INTEGER)
                            ps.setString(7, rs.getString("data_json"))
                            setUuidParam(ps, 8, newUserUuid, isPostgres)
                            setTimestampParam(ps, 9, rs.getString("created_at"), isPostgres)
                            ps.setBoolean(10, rs.getBoolean("is_prescout"))
                            ps.setBoolean(11, rs.getBoolean("has_discrepancy"))
                            ps.setString(12, rs.getString("conflicting_teams") ?: "")
                            ps.executeUpdate()
                        }
                        count++
                    }
                    println("[DB Migration] Migrated $count rows from $srcTable")
                }
            }
        } catch (_: Exception) {}
    }

    private fun copyConfigTable(c: java.sql.Connection, srcTable: String, dstTable: String, isPostgres: Boolean) {
        try {
            tableExistsOld(c, srcTable, isPostgres) {
                c.createStatement().executeQuery("SELECT team_number, config_json, updated_at FROM \"$srcTable\"").use { rs ->
                    while (rs.next()) {
                        c.prepareStatement("INSERT INTO $dstTable (id, team_number, config_json, updated_at) VALUES (?, ?, ?, ?) ON CONFLICT (team_number) DO NOTHING").use { ps ->
                            setUuidParam(ps, 1, UUID.randomUUID(), isPostgres)
                            ps.setInt(2, rs.getInt("team_number"))
                            ps.setString(3, rs.getString("config_json"))
                            setTimestampParam(ps, 4, rs.getString("updated_at"), isPostgres)
                            ps.executeUpdate()
                        }
                    }
                }
            }
        } catch (_: Exception) {}
    }

    private fun buildSqliteUrl(config: DatabaseConfig): String {
        val filePath = Paths.get(config.sqlite.file)
        filePath.parent?.let { Files.createDirectories(it) }
        return "jdbc:sqlite:${filePath.toString()}?journal_mode=WAL&busy_timeout=5000&synchronous=NORMAL"
    }

    private fun buildPostgresUrl(config: DatabaseConfig): String {
        val base = "jdbc:postgresql://${config.postgres.host}:${config.postgres.port}/${config.postgres.database}"
        return if (config.postgres.ssl) {
            "$base?sslmode=require"
        } else {
            "$base?sslmode=disable"
        }
    }

    /**
     * Connects to the default "postgres" maintenance database and creates the
     * target database if it does not already exist.  PostgreSQL does not support
     * CREATE DATABASE inside a transaction, so we use autoCommit = true on a
     * plain JDBC connection rather than going through Exposed/HikariCP.
     */
    private fun ensurePostgresDatabaseExists(config: DatabaseConfig) {
        val pg = config.postgres
        ensureJdbcDriverLoaded("postgres")
        // Identifiers in PostgreSQL are case-folded to lower-case unless quoted.
        val dbName = pg.database.lowercase()
        
        // Database name is validated to be lowercase alphanumeric+underscore
        // to prevent SQL injection or connection issues.
        require(dbName.matches(Regex("[a-z0-9_]+"))) {
            "Postgres database name must contain only lowercase letters, digits, and underscores."
        }

        val sslSuffix = if (pg.ssl) "?sslmode=require" else "?sslmode=disable"
        val maintenanceUrl = "jdbc:postgresql://${pg.host}:${pg.port}/postgres$sslSuffix"
        DriverManager.getConnection(maintenanceUrl, pg.user, pg.password).use { conn ->
            conn.autoCommit = true
            conn.createStatement().use { stmt ->
                val exists = conn
                    .prepareStatement("SELECT 1 FROM pg_database WHERE datname = ?")
                    .also { it.setString(1, dbName) }
                    .executeQuery()
                    .next()
                if (!exists) {
                    stmt.execute("CREATE DATABASE \"$dbName\"")
                    println("Created PostgreSQL database: $dbName")
                }
            }
        }
    }

    private fun ensureJdbcDriverLoaded(type: String) {
        when (type.lowercase()) {
            "postgres" -> Class.forName("org.postgresql.Driver")
            else -> Class.forName("org.sqlite.JDBC")
        }
    }
}
